name: graphql_test_new
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.1.0
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  retrofit: ^3.0.0
  flutter_svg: ^1.0.0
  auto_route: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  freezed: ^1.0.2
  json_serializable: ^6.1.1
  injectable: ^1.5.0
  injectable_generator: ^1.5.2
  retrofit_generator: ^3.0.0+2
  auto_route_generator: ^3.2.3
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/system/logo.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1a1a1a"
  image: assets/system/logo.png
  image_dark: assets/system/logo.png
  android_12:
    image: assets/system/logo.png
    image_dark: assets/system/logo.png
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#1a1a1a"
  android: true
  ios: true  
